### ISSUE TITLE
Encountered error: Uncaught Error: c: Cannot read property 'getExtension' of null in src/issues.js

### ISSUE THREAD

**Issue by rbharath** [Strilanc/Quirk#162]
I tried Quirk out on my browser (Chrome 49 on Ubuntu 12.04) and ran into the following issues (auto-included). Any pointers much appreciated!

URL
http://algorithmicassertions.com/quirk

BROWSER
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
Netscape
5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

ERROR OBJECT
Error: c: Cannot read property 'getExtension' of null in src/issues.js

ERROR LOCATION
c: Cannot read property 'getExtension' of null
    at a (src.min.js:1339:182)
    at src.min.js:1345:8
    at b.g.getUncoatedModule (src.min.js:23:23)
    at Object.r.get [as getModule] (src.min.js:28:51)
    at src.min.js:1348:17
    at b.g.getUncoatedModule (src.min.js:23:23)
    at Object.r.get [as getModule] (src.min.js:28:51)
    at src.min.js:1981:125
 loaded by src/main.js

**Comment by Strilanc** [comment]
Hmm, that's this line:

```javascript
function detectFloatTexturesNotSupported() {
    return document.createElement('canvas').getContext('webgl').getExtension('OES_texture_float') === null;
}
```

I think it's because I called getContext on 'webgl' but without the fallback to 'experimental-webgl' like this:

     canvas.getContext('webgl') || canvas.getContext('experimental-webgl')

If you **go to [this jsfiddle](https://jsfiddle.net/6y1dL4yy/1/)**, does the alert say `webgl,false,experimental-webgl,true`?

    alert([
        "webgl",
        document.createElement('canvas').getContext('webgl') !== null,
        "experimental-webgl",
        document.createElement('canvas').getContext('experimental-webgl') !== null])

**Comment by rbharath** [comment]
The jsfiddle says `webgl,false,experimental-webgl,false`. I'm guessing that the issue is that I don't have webgl enabled...

**Comment by Strilanc** [comment]
Yes, that might have something to do with it.

I'll add it as one of the 'known issue' detections, and fix the existing detection function not using the fallback.

Thanks for the report.

**Comment by Strilanc** [comment]
https://github.com/Strilanc/Quirk/commit/b396b919082c716769489f7934ddd0eb3abb887b adds the webgl-missing detection and fixes the existing detection not doing the experimental fallback.
