### ISSUE TITLE
Encountered error: Error: c: document.createElement(...).getContext(...) is null in src/issues.js

### ISSUE THREAD

**Issue by creekpld** [Strilanc/Quirk#165]
URL
http://algorithmicassertions.com/quirk

BROWSER
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0
Netscape
5.0 (X11)

ERROR OBJECT
Error: c: document.createElement(...).getContext(...) is null in src/issues.js

ERROR LOCATION
a@src.min.js:1339:130
@src.min.js:1345:8
g.prototype.getUncoatedModule@src.min.js:23:13
r.get@src.min.js:28:49
@src.min.js:1348:1
g.prototype.getUncoatedModule@src.min.js:23:13
r.get@src.min.js:28:49
@src.min.js:1981:109

 loaded by src/main.js

**Comment by Strilanc** [comment]
Thanks for the report.

Someone else reported a bug like this: https://github.com/Strilanc/Quirk/issues/162

Do you have webgl enabled?

**Comment by creekpld** [comment]
ok, webgl was disabled because i am running ubuntu in a VM.
maybe a litle script that checks for webgl support with a clear message would be nice.

**Comment by Strilanc** [comment]
That's the plan for resolving the other issue.
