### ISSUE TITLE
Encountered error: Uncaught Error: c: Cannot read property 'getExtension' of null in src/issues.js

### ISSUE THREAD

**Issue by creekpld** [Strilanc/Quirk#166]
URL
http://algorithmicassertions.com/quirk

BROWSER
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/50.0.2661.102 Chrome/50.0.2661.102 Safari/537.36
Netscape
5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/50.0.2661.102 Chrome/50.0.2661.102 Safari/537.36

ERROR OBJECT
Error: c: Cannot read property 'getExtension' of null in src/issues.js

ERROR LOCATION
c: Cannot read property 'getExtension' of null
    at a (src.min.js:1339:182)
    at src.min.js:1345:8
    at b.g.getUncoatedModule (src.min.js:23:23)
    at Object.r.get [as getModule] (src.min.js:28:51)
    at src.min.js:1348:17
    at b.g.getUncoatedModule (src.min.js:23:23)
    at Object.r.get [as getModule] (src.min.js:28:51)
    at src.min.js:1981:125
 loaded by src/main.js

**Comment by Strilanc** [comment]
Equivalent to the other issue your reported ( https://github.com/Strilanc/Quirk/issues/165 ), so I'll close this one.
