### ISSUE TITLE
Self-contained saved circuits as an html file

### ISSUE THREAD

**Issue by Strilanc** [Strilanc/Quirk#167]
Someone emailed me, asking about the ability to save a circuit that would work offline twenty years from now.

This is probably a good idea. Basically I'd want to be able to generate an HTML file that contained all the necessary ingredients, including both a script tag containing the contents of src.min.js and an extra script tag to force the loading of the desired circuit.

**Comment by stared** [comment]
Isn't the JSON encoding enough? (As it is now in the address.)

**Comment by Strilanc** [comment]
It's a slightly different use case.

If I think of a clever way to dynamically pack the html and javascript + circuit-to-load into a single html file, it would fit right in as an option in the export menu (if that's added).

**Comment by stared** [comment]
You mean - rather a standalone single-html file? It is possible.

http://jsfiddle.net/a856P/51/ for generating links with custom downloads.
(I use it in my Quantum Game, but only for creating JSON files describing;
I hope that there are no bottlenecks with it's size.)

**Comment by Strilanc** [comment]
https://github.com/Strilanc/Quirk/pull/180/commits/0a63072597688808e90c74f39b2580cf5bb1c486

- Overrides the ctrl+s save behavior so that it outputs a self-contained html file that contains quirk and defaults to the current circuit when opened.

I'll probably drop the ctrl+s override, since it's not a reliable way to override that particular behavior (i.e. file->save will behave differently, users using differrent OSs with different key combinations won't get it, etc).
