### ISSUE TITLE
Chrome 61 shader compiler issue

### ISSUE THREAD

**Issue by ebraminio** [Strilanc/Quirk#378]
I usually use macOS with Safari so I didn't see this until recently that on a Windows box there is a compile issue that it seems if I put any of gate on the circuit, for example [this circuit](http://algassert.com/quirk#circuit=%7B%22cols%22%3A%5B%5B%22Z%5Et%22%5D%5D%7D) on a "Version 61.0.3163.79 (Official Build) beta (64-bit)" on a Windows machine I will get this: 

```
Recovered from an error. :(
Defaulted to NaN results. Computing circuit values failed. (WebGLShader: Shader compile failed.
Info: ERROR: 0:18: 'webgl_286cc28ba4512e72' : undeclared identifier
ERROR: 0:18: 'assign' : l-value required (can't modify a const)
ERROR: 0:19: 'webgl_d95d8e9804629e71' : undeclared identifier
ERROR: 0:19: 'assign' : l-value required (can't modify a const)

Source: 
precision highp float;
precision highp int;

///////////// makeFloatCoderInput(2, ketgen_ket) ////////////
uniform sampler2D _gen_ketgen_ket_tex;
uniform vec2 _gen_ketgen_ket_size;

vec2 read_ketgen_ket(float k) {
vec2 uv = vec2(mod(k, _gen_ketgen_ket_size.x) + 0.5,
floor(k / _gen_ketgen_ket_size.x) + 0.5) / _gen_ketgen_ket_size;
return texture2D(_gen_ketgen_ket_tex, uv).xy;
}

float len_ketgen_ket() {
return _gen_ketgen_ket_size.x * _gen_ketgen_ket_size.y;
}
///////////// boolInput(ketgen_control) ////////////
uniform sampler2D _gen_ketgen_control_tex;
uniform vec2 _gen_ketgen_control_size;

float read_ketgen_control(float k) {
vec2 uv = vec2(mod(k, _gen_ketgen_control_size.x) + 0.5,
floor(k / _gen_ketgen_control_size.x) + 0.5) / _gen_ketgen_control_size;
return float(texture2D(_gen_ketgen_control_tex, uv).x == 1.0);
}

float len_ketgen_control() {
return _gen_ketgen_control_size.x * _gen_ketgen_control_size.y * 4.0;
}
///////////// makeFloatCoderOutput2 ////////////
vec2 outputFor(float k);

uniform vec2 _gen_output_size;
uniform float _gen_secret_half;

float len_output() {
return _gen_output_size.x * _gen_output_size.y;
}

void main() {
vec2 xy = gl_FragCoord.xy - vec2(_gen_secret_half, _gen_secret_half);
float k = xy.y * _gen_output_size.x + xy.x;

vec2 v = outputFor(k);

gl_FragColor = vec4(v.x, v.y, 0.0, 0.0);
}
//////// tail ////////

uniform float _ketgen_step;

float _ketgen_off;
float full_out_id;

vec2 cmul(vec2 c1, vec2 c2) { return mat2(c1.x, c1.y, -c1.y, c1.x) * c2; }
vec2 inp(float k) { return read_ketgen_ket(_ketgen_off + _ketgen_step*k); }

uniform vec2 a, b, c, d;

vec2 _ketgen_output_for(float out_id, vec2 amp) {
return cmul(inp(0.0), a+(c-a)*out_id) + cmul(inp(1.0), b+(d-b)*out_id);
}

vec2 outputFor(float k) {
full_out_id = k;

float relevant_out_id = mod(floor(full_out_id / _ketgen_step), 2.0);
_ketgen_off = full_out_id - relevant_out_id*_ketgen_step;

float c = read_ketgen_control(full_out_id);
vec2 vc = read_ketgen_ket(full_out_id);
vec2 vt = _ketgen_output_for(relevant_out_id, vc);
return (1.0-c)*vc + c*vt;
})

Please report it:
Create an issue on github (requires an account) (repository: Strilanc/Quirk)
or Email the issue to craig.gidney@gmail.com


Useful details to mention (auto-included if you use the create/email links above):

Defaulted to NaN results. Computing circuit values failed.

URL
http://algassert.com/quirk#circuit={"cols":[["Z^t"]]}

BROWSER
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36
Netscape
5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36

RECOVERY DETAILS
{"circuitDefinition": {"cols": [["Z^t"]]}}

ERROR OBJECT
Error: WebGLShader: Shader compile failed.
Info: ERROR: 0:18: 'webgl_286cc28ba4512e72' : undeclared identifier
ERROR: 0:18: 'assign' : l-value required (can't modify a const)
ERROR: 0:19: 'webgl_d95d8e9804629e71' : undeclared identifier
ERROR: 0:19: 'assign' : l-value required (can't modify a const)

Source: 
precision highp float;
precision highp int;

///////////// makeFloatCoderInput(2, ketgen_ket) ////////////
uniform sampler2D _gen_ketgen_ket_tex;
uniform vec2 _gen_ketgen_ket_size;

vec2 read_ketgen_ket(float k) {
vec2 uv = vec2(mod(k, _gen_ketgen_ket_size.x) + 0.5,
floor(k / _gen_ketgen_ket_size.x) + 0.5) / _gen_ketgen_ket_size;
return texture2D(_gen_ketgen_ket_tex, uv).xy;
}

float len_ketgen_ket() {
return _gen_ketgen_ket_size.x * _gen_ketgen_ket_size.y;
}
///////////// boolInput(ketgen_control) ////////////
uniform sampler2D _gen_ketgen_control_tex;
uniform vec2 _gen_ketgen_control_size;

float read_ketgen_control(float k) {
vec2 uv = vec2(mod(k, _gen_ketgen_control_size.x) + 0.5,
floor(k / _gen_ketgen_control_size.x) + 0.5) / _gen_ketgen_control_size;
return float(texture2D(_gen_ketgen_control_tex, uv).x == 1.0);
}

float len_ketgen_control() {
return _gen_ketgen_control_size.x * _gen_ketgen_control_size.y * 4.0;
}
///////////// makeFloatCoderOutput2 ////////////
vec2 outputFor(float k);

uniform vec2 _gen_output_size;
uniform float _gen_secret_half;

float len_output() {
return _gen_output_size.x * _gen_output_size.y;
}

void main() {
vec2 xy = gl_FragCoord.xy - vec2(_gen_secret_half, _gen_secret_half);
float k = xy.y * _gen_output_size.x + xy.x;

vec2 v = outputFor(k);

gl_FragColor = vec4(v.x, v.y, 0.0, 0.0);
}
//////// tail ////////

uniform float _ketgen_step;

float _ketgen_off;
float full_out_id;

vec2 cmul(vec2 c1, vec2 c2) { return mat2(c1.x, c1.y, -c1.y, c1.x) * c2; }
vec2 inp(float k) { return read_ketgen_ket(_ketgen_off + _ketgen_step*k); }

uniform vec2 a, b, c, d;

vec2 _ketgen_output_for(float out_id, vec2 amp) {
return cmul(inp(0.0), a+(c-a)*out_id) + cmul(inp(1.0), b+(d-b)*out_id);
}

vec2 outputFor(float k) {
full_out_id = k;

float relevant_out_id = mod(floor(full_out_id / _ketgen_step), 2.0);
_ketgen_off = full_out_id - relevant_out_id*_ketgen_step;

float c = read_ketgen_control(full_out_id);
vec2 vc = read_ketgen_ket(full_out_id);
vec2 vt = _ketgen_output_for(relevant_out_id, vc);
return (1.0-c)*vc + c*vt;
}

ERROR LOCATION
Error: WebGLShader: Shader compile failed.
Info: ERROR: 0:18: 'webgl_286cc28ba4512e72' : undeclared identifier
ERROR: 0:18: 'assign' : l-value required (can't modify a const)
ERROR: 0:19: 'webgl_d95d8e9804629e71' : undeclared identifier
ERROR: 0:19: 'assign' : l-value required (can't modify a const)

Source: 
precision highp float;
precision highp int;

///////////// makeFloatCoderInput(2, ketgen_ket) ////////////
uniform sampler2D _gen_ketgen_ket_tex;
uniform vec2 _gen_ketgen_ket_size;

vec2 read_ketgen_ket(float k) {
vec2 uv = vec2(mod(k, _gen_ketgen_ket_size.x) + 0.5,
floor(k / _gen_ketgen_ket_size.x) + 0.5) / _gen_ketgen_ket_size;
return texture2D(_gen_ketgen_ket_tex, uv).xy;
}

float len_ketgen_ket() {
return _gen_ketgen_ket_size.x * _gen_ketgen_ket_size.y;
}
///////////// boolInput(ketgen_control) ////////////
uniform sampler2D _gen_ketgen_control_tex;
uniform vec2 _gen_ketgen_control_size;

float read_ketgen_control(float k) {
vec2 uv = vec2(mod(k, _gen_ketgen_control_size.x) + 0.5,
floor(k / _gen_ketgen_control_size.x) + 0.5) / _gen_ketgen_control_size;
return float(texture2D(_gen_ketgen_control_tex, uv).x == 1.0);
}

float len_ketgen_control() {
return _gen_ketgen_control_size.x * _gen_ketgen_control_size.y * 4.0;
}
///////////// makeFloatCoderOutput2 ////////////
vec2 outputFor(float k);

uniform vec2 _gen_output_size;
uniform float _gen_secret_half;

float len_output() {
return _gen_output_size.x * _gen_output_size.y;
}

void main() {
vec2 xy = gl_FragCoord.xy - vec2(_gen_secret_half, _gen_secret_half);
float k = xy.y * _gen_output_size.x + xy.x;

vec2 v = outputFor(k);

gl_FragColor = vec4(v.x, v.y, 0.0, 0.0);
}
//////// tail ////////

uniform float _ketgen_step;

float _ketgen_off;
float full_out_id;

vec2 cmul(vec2 c1, vec2 c2) { return mat2(c1.x, c1.y, -c1.y, c1.x) * c2; }
vec2 inp(float k) { return read_ketgen_ket(_ketgen_off + _ketgen_step*k); }

uniform vec2 a, b, c, d;

vec2 _ketgen_output_for(float out_id, vec2 amp) {
return cmul(inp(0.0), a+(c-a)*out_id) + cmul(inp(1.0), b+(d-b)*out_id);
}

vec2 outputFor(float k) {
full_out_id = k;

float relevant_out_id = mod(floor(full_out_id / _ketgen_step), 2.0);
_ketgen_off = full_out_id - relevant_out_id*_ketgen_step;

float c = read_ketgen_control(full_out_id);
vec2 vc = read_ketgen_ket(full_out_id);
vec2 vt = _ketgen_output_for(relevant_out_id, vc);
return (1.0-c)*vc + c*vt;
}
at Function.compileShader (http://algassert.com/quirk:2956:110)
at new e (http://algassert.com/quirk:2946:453)
at a.initializer (http://algassert.com/quirk:2941:66)
at a.initializedValue (http://algassert.com/quirk:2932:79)
at a.renderToFunc (http://algassert.com/quirk:2943:122)
at a.renderTo (http://algassert.com/quirk:2903:126)
at a.renderToFunc (http://algassert.com/quirk:2842:76)
at a.renderTo (http://algassert.com/quirk:2903:126)
at b.shadeAndTrade (http://algassert.com/quirk:2995:3)
at b.applyOperation (http://algassert.com/quirk:1285:115)

COVERED
(Recovered) Defaulted to NaN results. Computing circuit values failed. @ Error: WebGLShader: Shader compile failed.
Info: ERROR: 0:18: 'webgl_286cc28ba4512e72' : undeclared identifier
ERROR: 0:18: 'assign' : l-value required (can't modify a const)
ERROR: 0:[...]

PRE-DRAWN 
```

**Comment by Strilanc** [comment]
Strange. The compile error is talking about the identifier `webgl_286cc28ba4512e72` (and similar), but that doesn't appear anywhere in the shader.

My uninformed guess is that the shader is hitting a bug in one your GPU drivers.

What kind of GPU does your machine have? Does this also happen in other browsers (e.g. Edge)? Does updating drivers make the bug go away?

**Comment by ebraminio** [comment]
Intel HD4600+[disabled] NVidia Quadro. Both Firefox and Edge work fine. They are fairly but I should try that.

The about:gpu logs contains lots of these, perhaps the `webgl_d95d8e9804629e71` is injected by angle or something, perhpas I should fill a bug on Chrome's bug tracker if these don't ring any bell there,

* [2376:11800:0910/134249.201:WARNING:angle_platform_impl.cc(41)] : rx::HLSLCompiler::compileToBinary(224): C:\fakepath(69,10-34): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them C:\fakepath(91,10-34): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
* [2376:2432:0911/235534.666:WARNING:angle_platform_impl.cc(41)] : gl::Shader::resolveCompile(329): ERROR: 0:18: 'webgl_286cc28ba4512e72' : undeclared identifier ERROR: 0:18: 'assign' : l-value required (can't modify a const) ERROR: 0:19: 'webgl_d95d8e9804629e71' : undeclared identifier ERROR: 0:19: 'assign' : l-value required (can't modify a const)
* [2376:2432:0911/235534.666:ERROR:shader_manager.cc(116)] : Shader translator allowed/produced an invalid shader unless the driver is buggy: --Log from shader translator-- --original-shader-- precision highp float; precision highp int; uniform sampler2D _gen_ketgen_ket_tex; uniform vec2 _gen_ketgen_ket_size; vec2 read_ketgen_ket(float k) { vec2 uv = vec2(mod(k, _gen_ketgen_ket_size.x) + 0.5, floor(k / _gen_ketgen_ket_size.x) + 0.5) / _gen_ketgen_ket_size; return texture2D(_gen_ketgen_ket_tex, uv).xy; } float len_ketgen_ket() { return _gen_ketgen_ket_size.x * _gen_ketgen_ket_size.y; } uniform sampler2D _gen_ketgen_control_tex; uniform vec2 _gen_ketgen_control_size; float read_ketgen_control(float k) { vec2 uv = vec2(mod(k, _gen_ketgen_control_size.x) + 0.5, floor(k / _gen_ketgen_control_size.x) + 0.5) / _gen_ketgen_control_size; return float(texture2D(_gen_ketgen_control_tex, uv).x == 1.0); } float len_ketgen_control() { return _gen_ketgen_control_size.x * _gen_ketgen_control_size.y * 4.0; } vec2 outputFor(float k); uniform vec2 _gen_output_size; uniform float _gen_secret_half; float len_output() { return _gen_output_size.x * _gen_output_size.y; } void main() { vec2 xy = gl_FragCoord.xy - vec2(_gen_secret_half, _gen_secret_half); float k = xy.y * _gen_output_size.x + xy.x; vec2 v = outputFor(k); gl_FragColor = vec4(v.x, v.y, 0.0, 0.0); } uniform float _ketgen_step; float _ketgen_off; float full_out_id; vec2 cmul(vec2 c1, vec2 c2) { return mat2(c1.x, c1.y, -c1.y, c1.x) * c2; } vec2 inp(float k) { return read_ketgen_ket(_ketgen_off + _ketgen_step*k); } uniform vec2 a, b, c, d; vec2 _ketgen_output_for(float out_id, vec2 amp) { return cmul(inp(0.0), a+(c-a)*out_id) + cmul(inp(1.0), b+(d-b)*out_id); } vec2 outputFor(float k) { full_out_id = k; float relevant_out_id = mod(floor(full_out_id / _ketgen_step), 2.0); _ketgen_off = full_out_id - relevant_out_id*_ketgen_step; float c = read_ketgen_control(full_out_id); vec2 vc = read_ketgen_ket(full_out_id); vec2 vt = _ketgen_output_for(relevant_out_id, vc); return (1.0-c)*vc + c*vt; } --translated-shader-- --info-log-- ERROR: 0:18: 'webgl_286cc28ba4512e72' : undeclared identifier ERROR: 0:18: 'assign' : l-value required (can't modify a const) ERROR: 0:19: 'webgl_d95d8e9804629e71' : undeclared identifier ERROR: 0:19: 'assign' : l-value required (can't modify a const)

**Comment by ebraminio** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=764036

**Comment by ebraminio** [comment]
From the Chromium bug:

> This issue is related to global variable initialization. If a global variable is declared after main(), it's not visible where ANGLE tries to initialize it. Here's a simpler shader to reproduce the issue:
>
> void main() {
>     gl_FragColor = vec4(0.0);
> }
>
> mediump float f;
>
> It should be pretty simple to fix, I'll try to have a fix for ANGLE ready for review today. While the bug exists in the browser, apps can work around it by declaring their globals in the beginning of the shader.

I am not sure if this is the case but the issue will soon hit stable Chrome versions so I guess the solution worths to be checked.

**Comment by Strilanc** [comment]
There aren't any post-declared variables in the generated shader source from the error trace.

Could it be the function `vec2 outputFor(float k)`? Its declaration is before usage, but the implementation is after usage.

Could it be that the variables can't come after *any* code? The shader is divided into separately generated parts that each declare their own uniforms.

**Comment by ebraminio** [comment]
I applied this patch and Chrome beta, even on macOS which had issue before the patch, now works fine. Should I apply it as PR or you have better solution for it?

```
diff --git a/src/webgl/ShaderCoders.js b/src/webgl/ShaderCoders.js
index e2fb7a0..eb60b55 100644
--- a/src/webgl/ShaderCoders.js
+++ b/src/webgl/ShaderCoders.js
@@ -158,7 +158,7 @@ function combinedShaderPartsWithCode(shaderPartsOrDescs, tailCode) {
             }
         }
         let libCode = [...libs, ...shaderPartDescs.map(e => e.toConcretePart().code)].join('');
-        return libCode + '\n//////// tail ////////\n' + tailCode;
+        return libCode.replace('void main()', '\n//////// tail ////////\n' + tailCode + '\n//////// main ////////\nvoid main()');
     };
 
     return new WglShader(sourceMaker);
```

**Comment by ebraminio** [comment]
In a nutshell, tail and the variable it initializes should come before main, what above patch/hack does.

**Comment by Strilanc** [comment]
Feel free to make a PR. I'll likely do something slightly different, but it's good to have the alternatives ready to go.

**Comment by ebraminio** [comment]
Great. Please consider putting the fixed version online. Thanks
