### ISSUE TITLE
Test September 2017 Release

### ISSUE THREAD

**Issue by Strilanc** [Strilanc/Quirk#383]
Platforms:

- [x] android/chrome
- [x] android/firefox
- [x] ios/safari
- [x] osx/safari
- [x] windows/firefox
- [x] windows/chrome
- [x] windows/edge
- [x] windows/internet explorer
- [x] ubuntu/chrome
- [x] ubuntu/firefox

Features:

- [x] Offline save
- [x] Example circuits work
- [x] Circuit editing (add, remove, move, undo, redo, column drag)
- [x] History (landing circuit entry stays for non-empty circuits)
- [x] Gate creation
- [x] Run test page
- [x] Run test perf page
- [x] Error reporting
- [x] Webgl disabled

**Comment by Strilanc** [comment]
Done

**Comment by ebraminio** [comment]
Fantastic work here! Thanks!
