### ISSUE TITLE
Add clickable toggles for the inputs.

### ISSUE THREAD

**Issue by georgir** [Strilanc/Quirk#389]
The starting state of each qubit always being 0 can be worked around by placing some "not" gates, but that's a somewhat annoying operation when you want to try out what a circuit does with different inputs. Add a simpler way to change the inputs with just one click instead of having to add and remove "not" gates with drag&drop.

**Comment by Strilanc** [comment]
The main reason I haven't done this is that I expect to forget I toggled an input, but not to forget I have an X gate. But I guess I can just make it visually stick out a lot.

BTW for trying out different inputs to a circuit, I recommend cycling through them with the dynamic counting gate, or even better the 'entanglement trick' for seeing the matrix of an operation:

![image](https://user-images.githubusercontent.com/79941/31193242-67cc61c6-a8f8-11e7-8a6e-48b0ae9563d2.png)

**Comment by lvandeve** [comment]
I would also love to be able to easily toggle between |0> and |1> at the inputs. It's more convenient than dragging an X there.

|1>'s at the input do not seem like total nonsense, e.g. Wikipedia's diagraom for Shor's algorithm has one:
https://en.wikipedia.org/wiki/File:Shor%27s_algorithm.svg
