### ISSUE TITLE
Recent version of Chrome on Linux throw NaNs

### ISSUE THREAD

**Issue by wd5gnr** [Strilanc/Quirk#398]
I have used Quirk before but after a recent upgrade of Chrome on Linux (64 bit) any circuit gives NaNs for any measurement (mine or the demo ones). I am not sure if the culprit is Chrome or a change in the simulator. Firefox on Linux works as does Chrome under Windows.

Both recent Chrome production and beta are affected. This also occurs in a private window, so I do not think it is extension related.

**Comment by Strilanc** [comment]
Hmm, sounds serious. Though Quirk definitely isn't giving NaNs in updated/preview Chrome instances on two machines I have.

When you try this it just shows NaN results? There's no other indication of error, like the big yellow report-error box thing showing up at the bottom of the page?

Is there any error or warning output to the console? (Hit ctrl+shift+J to see Chrome's console.)

Does the same thing happen in firefox?

Did you also upgrade other things at the same time (e.g. GPU drivers)?

**Comment by wd5gnr** [comment]
No yellow. Firefox works. Hard to say what exactly broke it as far as
upgrades.

All measures show NaN no matter what. I opened the console earlier and
didn't see anything obvious but I'll look again.

**Comment by wd5gnr** [comment]
Working now. By the way, Quirk was featured today on Hackaday ;-)

**Comment by Strilanc** [comment]
Whaaaaaaaaat, that's awesome!
