### ISSUE TITLE
Shortcut to delet selected gates or gate cobination

### ISSUE THREAD

**Issue by AbdallaEssamAli** [Strilanc/Quirk#407]

**Comment by AbdallaEssamAli** [comment]
I hope you can add a shortcut to delete selected gate or gate combination (column). By selected gates I mean the gates selected when using `ctrl` key.

![quirk_featurerequest01](https://user-images.githubusercontent.com/10597197/42851375-a9aa07cc-8a2c-11e8-8f0f-3bcec7025cc1.jpg)

**Comment by Strilanc** [comment]
I could remove the code that clamps the column into the circuit, and allow it to be dragged away.

**Comment by NoLongerBreathedIn** [comment]
Weirdly, it does this sporadically on OSX; this probably has to do with ctl not being remapped to cmd.

**Comment by Strilanc** [comment]
Fixed by https://github.com/Strilanc/Quirk/pull/404/commits/6da666c6fca583c14943588a7873f357b2af594f . Will be in next release.
