### ISSUE TITLE
Create a new Gate that accept input

### ISSUE THREAD

**Issue by AbdallaEssamAli** [Strilanc/Quirk#408]
Is it possible to create a gate that accept inputs the same way the **Compare** gates do ?
If not possible please try to add this feature as soon as you can...

And  of course, thank you for your awesome simulator...

**Comment by Strilanc** [comment]
There is limited support for creating custom gates that accept inputs. The trick is to put input-requiring gates inside of the custom gate, and then supply the inputs from the outside.

For example, put two +A gates into the circuit, then create a custom circuit gate:

![image](https://user-images.githubusercontent.com/79941/42862756-be44edd0-8a15-11e8-8f00-2ed99e047f21.png)

And then you have a fancy new gate:

![image](https://user-images.githubusercontent.com/79941/42862781-d01fbf80-8a15-11e8-8541-0a67ab7d23ef.png)

http://algassert.com/quirk#circuit=%7B%22cols%22%3A%5B%5B1%2C1%2C1%2C1%2C1%2C1%2C%22X%22%5D%2C%5B%22~vamp%22%2C1%2C1%2C1%2C1%2C1%2C%22inputA3%22%5D%5D%2C%22gates%22%3A%5B%7B%22id%22%3A%22~vamp%22%2C%22name%22%3A%22%2BA3%2CA3%22%2C%22circuit%22%3A%7B%22cols%22%3A%5B%5B%22%2B%3DA3%22%2C1%2C1%2C%22%2B%3DA3%22%5D%5D%7D%7D%5D%7D
