### ISSUE TITLE
Detectors shouldn't count as reducing total squared amplitude

### ISSUE THREAD

**Issue by Strilanc** [Strilanc/Quirk#409]
There is a technical sense in which a 50/50 measurement post-selects down to half of the cases, but people don't expect this behavior at all.

**Comment by NoLongerBreathedIn** [comment]
Perhaps change ‘omits 50%’ on the postselection to ‘50% failure’?
That would clarify some things.

**Comment by Strilanc** [comment]
Fixed in https://github.com/Strilanc/Quirk/pull/404/commits/25849af2cfc2eea931a1e2eab1ba31b9f81709ba
