### ISSUE TITLE
Question: What defines a radius (r) in Bloch sphere representation?

### ISSUE THREAD

**Issue by weekens** [Strilanc/Quirk#411]
I know this question might not strictly relate to Quirk, but anyway: what defines a radius (r) in Bloch sphere?

Suppose I prepared a [W state](https://en.wikipedia.org/wiki/W_state) for 4 quibits with [this circuit](http://algassert.com/quirk#circuit={%22cols%22:[[1,%22X%22,%22H%22,%22H%22],[1,%22X%22,1,%22%E2%80%A2%22],[%22X%22,1,%22%E2%80%A2%22],[%22%E2%80%A2%22,%22%E2%97%A6%22,1,%22X%22],[%22%E2%80%A2%22,%22%E2%97%A6%22,%22X%22],[%22X%22,%22%E2%80%A2%22,%22%E2%80%A2%22],[1,%22X%22,%22%E2%80%A2%22]]}).

In the given cicuit r=0.5 for all 4 quibuts. Does r define a measure of entanglement between qubits? Or I can make r=0.5 for one single qubit?

**Comment by Strilanc** [comment]
You should ask this question on the [quantum computing stack exchange](http://quantumcomputing.stackexchange.com/).

The radius tells you how close to a pure state the qubit is. A pure qubit has one specific direction along which you will always get the same measurement result; the direction of the bloch vector. Qubits can appear not-pure for two very distinct reasons: entanglement and uncertainty. The radius being less than 1 is a necessary condition for entanglement, but not a sufficient one, so it is a useful but unreliable signal.
