### ISSUE TITLE
Horizontal scrolling.

### ISSUE THREAD

**Issue by xayam** [Strilanc/Quirk#414]
It's bad that the toolbox is scrolling along with the qubits, they should have their own scrolling, otherwise with a large number of gates in width - the toolbox goes out of sight

**Comment by Strilanc** [comment]
The problem with locking the toolbox to the screen is that on some screens the toolbox doesn't fit.

**Comment by Strilanc** [comment]
Closing as WONTFIX. If someone wants to put in the effort to have the toolbox drag leftward in a way that still works on small screens, I will of course merge it.
