### ISSUE TITLE
Building Logic gate Computer Classes on Computer Quantum

### ISSUE THREAD

**Issue by foodmaher** [Strilanc/Quirk#422]
I need to build logical portals for classic computers on quantum computers such as these logical gates (and, or, not, xor, nand) and others, **how do I do this?**

Where their inputs and outputs will be located to measure them on a lines the Qubit ? ..

**Comment by Strilanc** [comment]
You store the result on a separate qubit. For example, the AND gate is emulated with a Toffoli (put a control on each of the inputs and a NOT gate on the output, all in the same column with the output starting in the 0 state).
