### ISSUE TITLE
question on Bell Inequality Test (CHSH)

### ISSUE THREAD

**Issue by delbert** [Strilanc/Quirk#430]
![Capture](https://user-images.githubusercontent.com/3459226/56474813-3969b880-644d-11e9-8cf0-762a85ff316e.PNG)

hello Everyone,

firstly, i apologize if this isn't the right place to post this question.  i looked at algassert.com and at Reddit and couldn't find anywhere to ask, so i thought i would try this.  if there is somewhere else, just let me know.

as far as i can tell, the Quirk example of the Bell Inequality Test (CHSH) is an example of the game described here:  https://www.pas.rochester.edu/assets/pdf/undergraduate/The_CHSH_game_as_a_Bell_test_thought_experiment.pdf

and i understand why the Chance Block of 84.5% is significant -- because it means that Alice and Bob have a strategy that helps them win the game at the quantum rate, as opposed to the classical rate (.75).  according to the rules, however, Alice and Bob are not allowed to communicate during the game, only to establish a strategy before hand,  but isn't that what they are doing when the doubly-controlled Not gate is being executed against the referee's input qubits?  (the 12th column in diagram -- the one circled on the attached image).

thanks for any insight,

delbert

**Comment by Strilanc** [comment]
Everything past the second set of "..."s is being done to determine the outcome of the game. It corresponds to the two referees coming together and comparing notes to check if Alice and Bob won or not. The only part that Alice and Bob are allowed to change is the middle part, and it's only in that part where operations may not cross between the two.

**Comment by delbert** [comment]
thanks!
