### ISSUE TITLE
Superconductor qubits physical gates

### ISSUE THREAD

**Issue by algonte** [Strilanc/Quirk#431]
It will be great to have on Quirk the physical gates that superconductor qubits provide, particularly on IBM QX physical gates are U1, U2 and U3. This would be very convinient in order to play with QAOA inside Quirk.
![ibm_qx_phys_gates](https://user-images.githubusercontent.com/44863589/56731611-2a3f7f00-675b-11e9-9d1f-a97c317c07b4.png)

**Comment by Strilanc** [comment]
Thank you for the suggestion.

Quirk doesn't have a concept of a gate with controllable parameters in the sense that would be necessary for this to work, and doing that is not high on my list of things to do unfortunately.

You do have access to these gates, in a somewhat clunky way, via the custom gates menu. You can enter their unitary matrix or the axis-angle equivalent. I think U3 is just an Rz(a) Ry(b) Rz(c) decomposition, so you can make custom Z, Y, and Z rotations and then create a custom circuit gate housing all three. This is tedious but it will work.

**Comment by algonte** [comment]
Thanks for your suggestion. In MaxCut application of QAOA the only required parameterized gates are Z and X, U3 was intended to implement parameterized X rotations but this can also be done with HZ(alpha)H. So, only Z(alpha) gates are required. This is the simplest "perfect" implementation for the trivial 2 nodes graph: https://algassert.com/quirk#circuit={%22cols%22:[[%22H%22,%22H%22],[%22%E2%80%A2%22,%22X%22],[1,%22Z^%C2%BD%22],[%22%E2%80%A2%22,%22X%22],[%22H%22,%22H%22],[%22Z^-%C2%BC%22,%22Z^-%C2%BC%22],[%22H%22,%22H%22]]}. In "more complex" graphs the problem is to set the number of cicles and the sequence of angles (¿?).
