### ISSUE TITLE
Sample on single wire is not stable. Is this expected behavior?

### ISSUE THREAD

**Issue by moudrick** [Strilanc/Quirk#433]
Sample on single wire is not stable. Is this expected behavior?
Not sure I am clearly understand what is Sample gate for. 

https://algassert.com/quirk#circuit={%22cols%22:[[%22Sample1%22]]}

**Comment by Strilanc** [comment]
Oh wow that is definitely not right. It's particularly strange how it seems to be limited to the single-qubit qubit-is-off case.

![image](https://user-images.githubusercontent.com/79941/57328440-4b429100-70c6-11e9-83a0-244d094aa8fd.png)

**Comment by Strilanc** [comment]
Fixed by https://github.com/Strilanc/Quirk/pull/438; will be in next release.
