### ISSUE TITLE
issue with custom cnot gate

### ISSUE THREAD

**Issue by GideonMax** [Strilanc/Quirk#437]
when using a cnot on state |+-> ( 0.5( |00> - |01> + |10> - |11>) ) the expected result is |--> ( 0.5( |00> - |01> + |10> - |11>)).
when using a normal cnot gate (control and pauli-x gate), the result is as expected, but when using a custom gate that is a cnot gate (from a matrix), the gate doesn't seem to have any effect on |+->, but it works fine in some other cases.
this is the matrix I used {{1,0,0,0},{0,1,0,0},{0,0,0,1},{0,0,1,0}}.

**Comment by Strilanc** [comment]
You've probably just got the bit ordering backwards. This can differ between programs. In Quirk the matrix you described is a CNOT with the control below the target, as opposed to a control above the target.
