### ISSUE TITLE
Assign the first qubit as the far left digit in the ket

### ISSUE THREAD

**Issue by Aljumaily** [Strilanc/Quirk#453]
The more standardized convention is that given two qubits |A⟩ and |B⟩ where |A⟩ is on the first (top) wire and |B⟩ is on second (bottom) wire, then, the chance functionality under the Displays section should have the tensor product as follows: |A⟩⊗|B⟩.
This should follow the standard binary numbering:
|A⟩⊗|B⟩
|0⟩⊗|0⟩ = decimal 0
|0⟩⊗|1⟩ = decimal 1
|1⟩⊗|0⟩ = decimal 2
|1⟩⊗|1⟩ = decimal 3.

**Comment by Strilanc** [comment]
Unfortunately, this is not going to be changed. Flipping this convention would break the fact that, via the state channel duality, the output display looks like the unitary matrix of the operation applied to one half of an entangled state.

![image](https://user-images.githubusercontent.com/79941/80758864-2e7b4680-8aeb-11ea-9c37-dd6de05d5c7a.png)
