### ISSUE TITLE
Building A Fork of Quirk, Not Completely Sure how circuit gates are stored.

### ISSUE THREAD

**Issue by abhobe** [Strilanc/Quirk#464]
I am building an extension of quirk which needs to check the order and type of gates in the circuit. How is this stored?

**Comment by Strilanc** [comment]
There is a class CircuitDefinition which has a list of columns, and each column has a list of positions that either contain a gate or nothing. Each gate has a height property that says how far down it extends from its starting position.

The relevant CircuitDefinition instances lives inside a DisplayedCircuit inside of a DisplayedInspector. The latest displayed inspector is inside an ObservableValue called `displayed` in main.
