### ISSUE TITLE
Bloch sphere display

### ISSUE THREAD

**Issue by dheerajpatankar** [Strilanc/Quirk#482]
I was trying few gates. Not sure if it's a real issue however Bloch sphere representation of both operations below is the same? Am I missing anything?

op1: X|0>
op2: Y|0>

Further if I modify the operations by adding another H gate for both operations, they also show same Bloch sphere representation.

**Comment by Strilanc** [comment]
That's the correct behavior. The two states are equal up to global phase.

**Comment by dheerajpatankar** [comment]
Thanks for the confirmation. Could you guide on how to show complex part on the bloch sphere as:
X|0>= |1> and Y|0> = i|1>
I tried searching any good article about this, appreciate any information.

**Comment by Strilanc** [comment]
The bloch sphere doesn't show that information, by design.
