### ISSUE TITLE
How can I convert a quantum circuit to and from QASM in javaScript? 

### ISSUE THREAD

**Issue by RelaxRick** [Strilanc/Quirk#504]
How can I convert a quantum circuit to and from QASM in javaScript?

**Comment by amirebrahimi** [comment]
We have a fork w/ some export functionality, but it isn't complete: https://github.com/Strilanc/Quirk/compare/master...adgt:Quirk:master

**Comment by RelaxRick** [comment]
Yes,  The current QASM export function can only export simple data, and complex data will prompt Invalid Circuit JSON, such as adding a controller. Is there a solution? bro.

**Comment by amirebrahimi** [comment]
If you have the time, I'd suggest to continue with what was started and if you are able to get complete support in, then perhaps @Strilanc might accept a PR. We didn't have time to complete it when we were working on our project, so we only added what we needed.

**Comment by RelaxRick** [comment]
Ok, but I don't know much about QASM's generation logic. Is there any document or website recommendation? I may improve the code in the future, thank you

**Comment by amirebrahimi** [comment]
The specification is here: https://openqasm.com/

**Comment by RelaxRick** [comment]
Got it, let me see

**Comment by Strilanc** [comment]
I'd definitely accept a PR with a QASM export. You can alternatively use cirq as a bridge since it has from_quirk and to_qasm. Closing this as it's more of a question than a request.
