### ISSUE TITLE
Minor UI issue in recent Firefox (starting at about Firefox 115)

### ISSUE THREAD

**Issue by cduck** [Strilanc/Quirk#506]
This is a bug in Firefox, not Quirk but you may want to track the issue here.  The horizontal qubit and measurement wires in the circuit diagram display are rendered as slight zig-zag lines instead of continuous, perfectly horizontal lines.

<img width="278" alt="firefox-canvas-bug" src="https://github.com/Strilanc/Quirk/assets/2476062/02ad6a89-d7cf-4880-bb49-2eb9d829bb4e">

See https://bugzilla.mozilla.org/show_bug.cgi?id=1847681 for more details.  At minimum this affects Firefox versions 115 through 116 (and 118 nightly) but it does not affect 109 (or earlier).

---

Quick-and-dirty fix that corrects the visual issue but breaks all other browsers (and the sampling gate icons):
[src/draw/Painter.js:451](https://github.com/Strilanc/Quirk/blob/8833791294e642795c8717038e84940a74b19a64/src/draw/Painter.js#L451)
```diff
-         this.ctx.moveTo(x1, y1);
+         this.ctx.moveTo(x1, y1+0.5);
```

**Comment by Strilanc** [comment]
Thanks for reporting this to Mozilla. I will sit back and watch.
